import type { ReactElement } from "react";
import type { Metadata } from "next";
import { fontsClassNames } from "@/fonts/fonts";
import Navbar from "@/components/Navbar";
import StoreProvider from "./store/StoreProvider";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<Props>) {
    return (
        <html lang="en">
            <body className={fontsClassNames}>
                <StoreProvider>
                    <Navbar />
                    <main>{children}</main>
                </StoreProvider>
            </body>
        </html>
    );
}
