import type { ReactElement } from "react";
import type { Metadata } from "next";
import { fontsClassNames } from "@/fonts/fonts";
import "@/fonts/fonts.css";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
};

export default function RootLayout({
    children,
}: Readonly<Props>): ReactElement {
    return (
        <html lang="en">
            <body className={fontsClassNames}>
                <Navbar />
                <main>{children}</main>
            </body>
        </html>
    );
}
